### ISSUE TITLE
空值是如何确定的？

### ISSUE THREAD

**Issue by Tongzhenguo** [wepe/DataCastle-Solution#6]
请问大神，您代码中将特征值小于0的判为空值是怎么确定的？是数据城堡运营告知的？还是您根据常识？

**Comment by wepe** [comment]
因为预处理的时候就将缺失的用负值填充了

**Comment by Tongzhenguo** [comment]
不太懂您的意思，您是说原来的赛题数据就已经做过负值填充了对吧？

**Comment by wepe** [comment]
不是，我处理的时候把缺失的用负值标志了。缺失这个从原始数据可以知道的

**Comment by Tongzhenguo** [comment]
多谢，不过令我更疑惑的是我拿到的赛题数据（http://www.pkbigdata.com/common/cmpt/微额借款用户人品预测大赛_赛体与数据.html#data）本来就是有负值（-1）的，换种方式问，我的意思是我跑您的代码不用再做一次负值填充了吧，因为貌似，现在数据都已经用负值标识了

**Comment by wepe** [comment]
新数据我就不太清楚了，如果是你说的那样，那就不用填充了

**Comment by Tongzhenguo** [comment]
ok,thanks
